services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: laravel_app
    volumes:
      - ./loyalty-service:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network

  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
      args:
        NODE_ENV: development   # change to "production" for prod
    container_name: react_app
    ports:
      - "5173:5173"  # dev port
      - "3000:3000"  # production port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
