version: "3.9"

services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network

  react:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    container_name: react_backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./laravel/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - react
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
